Update

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,1 +1,17 @@
-
+name: 01 - Building Blocks
+on: push
+jobs:
+    echo-hello:
+        runs-on: ubnuntu-latest
+        steps:
+            - name: Say Hello  
+              run: echo "Hello, world!"
+    echo-goodbye:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Failed Step
+              run: |
+                echo "This step will fail"
+                exit 1
+            - name: Say Goodbye
+              run: echo "Goodbye"
